module.exports = {
    title: 'title',
    description: 'description',
    logo: 'logo',
    icon: 'icon',
    brand: 'brand',
    cover_image: 'cover_image',
    facebook: 'facebook',
    twitter: 'twitter',
    default_locale: 'lang',
    active_timezone: 'timezone',
    // TODO: substitute ghost_head and ghost_foot with codeinjection_* when we drop v2 (Ghost 4.0)
    ghost_head: 'ghost_head',
    ghost_foot: 'ghost_foot',
    navigation: 'navigation',
    secondary_navigation: 'secondary_navigation',
    meta_title: 'meta_title',
    meta_description: 'meta_description',
    og_image: 'og_image',
    og_title: 'og_title',
    og_description: 'og_description',
    twitter_image: 'twitter_image',
    twitter_title: 'twitter_title',
    twitter_description: 'twitter_description'
};
